### ISSUE TITLE
Feature request: DefaultDeferredManager.when returns MultipleRejects

### ISSUE THREAD

**Issue by tramchamploo** [jdeferred/jdeferred#105]
I want to know exactly which deferred resolved or rejected. Seems it can't be achieved now.

**Comment by saturnism** [comment]
@tramchamploo thnx for the request! jdeferred semantic is based on jquery's deferred object semantic.

it'd be great if you could help propose what a new semantic should be for this, since if it needs to return multiple rejects, it'll have to wait for all promises to finish. I feel this may be similar to promises.all(...), similar to this:
https://github.com/jdeferred/jdeferred/pull/92/files#diff-a66a22d7b0c5e4f3f9a7906a2947ac31R112

**Comment by tramchamploo** [comment]
Since the all(...) method is assign to a different feature, it's really hard to think up a new semantic for this. So es6 doesn't have this feature yet?

**Comment by saturnism** [comment]
Here is an experimental implementation around es6 semantics:
https://github.com/jdeferred/jdeferred/pull/92/files

IIRC, the `all` semantic is also failing fast.

**Comment by saturnism** [comment]
This should be addressed by #128, ptal!
