### ISSUE TITLE
Cancel functionality 

### ISSUE THREAD

**Issue by korkag** [jdeferred/jdeferred#39]
Cancel functionality is missing:
Missing State.CANCELED with cancel() method and onCancel listener. If promise is in pending state and cancel method was called, move the state to CANCELED, call onCancel method.

**Comment by Wattos** [comment]
:+1: I would also advice for a cancel method. The solution above is might not make sense since you cannot reject a promise, only a deferred. The cancel should be on the promise.

In addition, it would probably make sense to have a seperate callback as a rejection usually implies failure not user choice

**Comment by lkho** [comment]
i've made a customization based on my needs/understanding: https://github.com/lkho/jdeferred/commit/0d233d3445df8d74a4c272524bf554bd190d809a
this also includes https://github.com/jdeferred/jdeferred/pull/50

hope this is useful

**Comment by saturnism** [comment]
Thanks @aalmiray!! This will be in for the next release!

**Comment by saturnism** [comment]
This was done in #126 Cheers!
